name: GBPUSD Bot

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile
        shell: pwsh
        run: |
          Write-Host "Checking repository..."
          Get-ChildItem -Recurse
